import http from './http'

export const api = {
  captcha: (uuid) => `${import.meta.env.VITE_API_ORIGIN || '/wx'}/captcha?uuid=${uuid}`,
  login: (data) => http.post('/sys/login', data),
  logout: () => http.post('/sys/logout'),
  me: () => http.get('/sys/user/info'),
  accounts: () => http.get('/manage/console/accounts'),
  context: () => http.get('/manage/console/context'),
  accountConfig: (appid) => http.get(`/manage/console/account-config/${appid}`),
  saveAccountConfig: (data) => http.post('/manage/console/account-config', data),
  followers: (params) => http.get('/manage/wxUser/list', { params }),
  syncFollowers: () => http.post('/manage/wxUser/syncWxUsers'),
  setFollowerRemark: (data) => http.post('/manage/wxUser/updateRemark', data),
  tags: () => http.get('/manage/wxUserTags/list'),
  saveTag: (data) => http.post('/manage/wxUserTags/save', data),
  deleteTag: (id) => http.post(`/manage/wxUserTags/delete/${id}`),
  batchTag: (data) => http.post('/manage/wxUserTags/batchTagging', data),
  batchUnTag: (data) => http.post('/manage/wxUserTags/batchUnTagging', data),
  materials: (params) => http.get('/manage/wxAssets/materialFileBatchGet', { params }),
  materialCount: () => http.get('/manage/wxAssets/materialCount'),
  uploadMaterial: (data) => http.post('/manage/wxAssets/materialFileUpload', data),
  deleteMaterial: (data) => http.post('/manage/wxAssets/materialDelete', data),
  menu: () => http.get('/manage/wxMenu/getMenu'),
  saveMenu: (data) => http.post('/manage/wxMenu/updateMenu', data),
  rules: (params) => http.get('/manage/msgReplyRule/list', { params }),
  saveRule: (data) => http.post('/manage/msgReplyRule/save', data),
  updateRule: (data) => http.post('/manage/msgReplyRule/update', data),
  deleteRules: (ids) => http.post('/manage/msgReplyRule/delete', ids),
  qrcodes: (params) => http.get('/manage/wxQrCode/list', { params }),
  createQrcode: (data) => http.post('/manage/wxQrCode/createTicket', data),
  deleteQrcodes: (ids) => http.post('/manage/wxQrCode/delete', ids),
  msgSessions: (params) => http.get('/manage/wxMsg/sessions', { params }),
  msgTimeline: (params) => http.get('/manage/wxMsg/timeline', { params }),
  msgMarkRead: (data) => http.post('/manage/wxMsg/read', data),
  msgUnreadCount: () => http.get('/manage/wxMsg/unread-count'),
  sendMsg: (data) => http.post('/manage/wxMsg/send', data),
  notifyChannels: (params) => http.get('/manage/notifyChannel/list', { params }),
  saveNotifyChannel: (data) => http.post('/manage/notifyChannel/save', data),
  updateNotifyChannel: (data) => http.post('/manage/notifyChannel/update', data),
  deleteNotifyChannels: (ids) => http.post('/manage/notifyChannel/delete', ids),
  regenerateNotifySecret: (id) => http.post(`/manage/notifyChannel/regenerateSecret/${id}`),
  closeNotifyGateway: (id) => http.post(`/manage/notifyChannel/closeGateway/${id}`),
  previewNotify: (data) => http.post('/manage/notifyChannel/preview', data),
  sendNotify: (data) => http.post('/manage/notifyChannel/send', data),
  notifyLogs: (params) => http.get('/manage/notifyChannel/logs', { params }),
}
